services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${GOHUNT_DB_USERNAME:-gohunt}
      - POSTGRES_PASSWORD=gohunt
      - POSTGRES_DB=gohunt
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${GOHUNT_DB_USERNAME:-gohunt}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data-dev:/var/lib/postgresql/data

  gohunt: 
    depends_on: 
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - GOHUNT_USERNAME=${GOHUNT_USERNAME}
      - GOHUNT_PASSWORD=${GOHUNT_PASSWORD}
      # Settings that can be configured either from the docker env, or config file
      - Domain=${DOMAIN}
      - ListenAddress=:8081
      - Features.Signup.Enabled=true
      - Notification.Webhooks.Enabled=true
      - Database.Host=postgres
      - Database.Port=5432
      - Database.User=${GOHUNT_DB_USERNAME:-gohunt}
      - Database.DBname=gohunt
      - Database.SSLmode=disable
      - Database.Password=gohunt
    ports:
      - 8081:8081

volumes:
  db-data-dev:
