services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=gohunt
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=gohunt
    volumes:
      - db-data:/var/lib/postgresql/data

  gohunt: 
    image: ghcr.io/nhas/gohunt:main
    environment:
      - GOHUNT_USERNAME=${GOHUNT_USERNAME}
      - GOHUNT_PASSWORD=${GOHUNT_PASSWORD}
      # Settings that can be configured either from the docker env, or config file
      - Domain=${DOMAIN}
      - ListenAddress=:8081
      - NumberProxies=1
      - Features.Signup.Enabled=true
      - Notification.Webhooks.Enabled=true
      - Database.Host=postgres
      - Database.Port=5432
      - Database.User=gohunt
      - Database.DBname=gohunt
      - Database.SSLmode=disabled
      - Database.Password=${DB_PASSWORD}

  caddy:
    image: caddy:2
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - caddy-data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  db-data:
  caddy-data:
  caddy_config: