services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=gohunt
      - POSTGRES_PASSWORD=gohunt
      - POSTGRES_DB=gohunt
    volumes:
      - db-data:/var/lib/postgresql/data

  gohunt: 
    image: ghcr.io/nhas/gohunt:main
    environment:
      - GOHUNT_USERNAME=${GOHUNT_USERNAME}
      - GOHUNT_PASSWORD=${GOHUNT_PASSWORD}
      # Settings that can be configured either from the docker env, or config file
      - Domain=${DOMAIN}
      - ListenAddress=:8081
      - Features.Signup.Enabled=true
      - Notification.Webhooks.Enabled=true
      - Database.Host=postgres
      - Database.Port=5432
      - Database.User=gohunt
      - Database.DBname=gohunt
      - Database.SSLmode=disable
      - Database.Password=gohunt
    ports:
      - 8081:8081

volumes:
  db-data:
  caddy-data:
  caddy_config: